spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource
    username: root
    password: 6677
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
